### ISSUE TITLE
Help icon button broken

### ISSUE THREAD

**Issue by ghost** [Anisotropic/Chameleon-blue#1]
As you can see here http://i.imgur.com/nJW3NhK.png

**Comment by Anisotropic** [comment]
Do you have a special plugin installed? Cause I don`t see this shortcut icons at my vannilla roundcube installation.

**Comment by ghost** [comment]
Yea, its called keyboard shortcut plugin i think. Its link [HERE](https://plugins.roundcube.net/packages/cor/keyboard_shortcuts)

**Comment by Anisotropic** [comment]
It is the issue with this plugin. In order to fix this broken icon you need to copy directory with keyboard icon and name it accordingly your chameleon installation. For example. If now you have "/plugins/keyboard_shortcuts/skins/larry/images/keyboard.png"  and your chameleon skin installed in "/skins/chameleon", so you need to copy "larry" directory to "chameleon". So it turn out into "/plugins/keyboard_shortcuts/skins/chameleon/images/keyboard.png" and this keyboard plugin will be able to insert keyboard icon into the page.
